#!/bin/bash

#This script loops through the files in current directory. Skips hidden files.

for file in * .*; do
    [[ "$file" == .* ]] && continue
    [[ -f "$file" ]] || continue
    echo "Processing, $file"
done
