#!/bin/bash

#This script uses two variables, making one of them local inside a function and the second one normal outside of it.


my_function() {
   local name="Changed"
   echo  "Inside: $name"
}

 name="Original" 
 my_function
 echo "Outside: $name"

