#!/bin/bash

#This script uses if/else statements to see if the argument is a file or directory.

if [[ -z "$1" || "$1" == "--help" ]]; then
   # Provide help to the script user.
    echo "Usage: $0 <filename>" 
    exit 1
fi

if [[ -f "$1" ]]; then
    echo "It's a file"
elif [[ -d "$1" ]]; then
    echo "It's a directory"
else
    echo "Not found: $1"
fi
